#include "common.h"
#include "gpio.h"
#include "tim.h"
#include "pwm.h"
#include "motor.h"
#include "board.h"
#include "prin.h"
#include "i2c.h"
#include "imu.h"
#include "SysTick.h" 
#include "FreeRTOS.h"
#include "task.h"
#include "rtos.h"

void main();